Repository Cheers-Project/Cheers-Back, pull requests merged in 2022-04, with the labels that each got.

#58 유저 정보 수정 API 구현
  src/api/user/index.js
  src/api/user/userController.js
  src/models/user.js
Labels: refactor, feature

#60 유저 정보 조회 API 리팩토링
  src/api/user/userController.js
Labels: refactor

#61 게시물 작성 API 작성, DB 생성
  src/api/board/boardController.js
  src/api/board/index.js
  src/api/index.js
  src/models/board.js
Labels: feature

#64 유저 정보 수정 API 추가 구현 및 jwt 로직 리팩토링
  src/api/auth/authController.js
  src/api/user/userController.js
  src/middleware/jwtMiddleware.js
  src/models/user.js
Labels: refactor, feature

#65 게시물 조회 API 구현
  src/api/board/boardController.js
  src/api/board/index.js
  src/api/user/userController.js
  src/models/board.js
Labels: feature

#67 게시물 API 필터링, 페이지네이션 추가
  src/api/board/boardController.js
  src/utils/pagination.js
Labels: feature

#69 모임 API 구현
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
  src/models/meeting.js
  src/models/user.js
Labels: feature

#72 마이 페이지 모임 요청 API 구현
  src/api/index.js
  src/api/meeting/meetingController.js
  src/api/my/index.js
  src/api/my/myController.js
  src/api/user/index.js
  src/api/user/userController.js
  src/models/meeting.js
Labels: refactor, feature

#74 게시물 API 수정
  package-lock.json
  package.json
  src/api/board/boardController.js
  src/api/board/index.js
  src/models/board.js
Labels: refactor, feature

#76 게시물 작성 API 수정
  src/api/board/boardController.js
  src/api/board/index.js
  src/middleware/sanitizeHtmlMiddleware.js
Labels: refactor

#78 모임 문서 수정
  src/api/meeting/meetingController.js
  src/api/my/myController.js
  src/models/meeting.js
Labels: refactor

#80 모임 API 조건부 처리 구현
  src/api/meeting/meetingController.js
  src/models/meeting.js
Labels: feature

#82 게시물 조회수 증가 API 수정
  src/api/board/boardController.js
  src/api/board/index.js
Labels: feature

#84 게시물 삭제 구현
  src/api/board/boardController.js
  src/api/board/index.js
  src/models/board.js
Labels: feature

#86 모임 요청 API 무한 요청 구현
  src/api/meeting/meetingController.js
Labels: refactor, feature

#88 게시물 요청 API 수정
  src/api/board/boardController.js
Labels: refactor

#91 모임 조회수 증가 API 구현
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
Labels: feature

#92 게시물 좋아요 API 구현
  src/api/board/boardController.js
  src/api/board/index.js
  src/models/board.js
Labels: feature

#94 내 게시물 API 구현
  src/api/my/index.js
  src/api/my/myController.js
Labels: feature

#97 모임 조회수 증가 API 수정
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
Labels: refactor

#98 게시물 조회 API 수정
  src/api/board/boardController.js
  src/api/board/index.js
Labels: refactor

#101 모임 수정 API 구현
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
Labels: feature

#102 게시물 수정 API 구현
  src/api/board/boardController.js
  src/api/board/index.js
Labels: feature

#104 모임 API 수정
  src/api/meeting/meetingController.js
  src/models/meeting.js
Labels: refactor

#105 모임 삭제 API 구현
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
Labels: feature

#110 댓글 작성 API 구현
  src/api/comment/commentController.js
  src/api/comment/index.js
  src/api/index.js
  src/models/comment.js
Labels: feature

#111 댓글 요청 API 구현
  src/api/comment/commentController.js
  src/api/comment/index.js
  src/models/comment.js
Labels: feature

#112 댓글 삭제 API 구현
  src/api/comment/commentController.js
  src/api/comment/index.js
Labels: feature

#114 모임 참여, 취소 구현
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
Labels: refactor

#116 내 모임 API 수정
  src/api/my/myController.js
Labels: refactor

#119 오류 메세지 통일, 불필요 log 제거
  src/api/auth/authController.js
  src/api/board/boardController.js
  src/api/comment/commentController.js
  src/middleware/sanitizeHtmlMiddleware.js
  src/models/board.js
Labels: refactor

#120 오류 메시지 통일 및 불필요 코드 제거
  src/api/meeting/meetingController.js
  src/api/my/myController.js
  src/api/user/userController.js
Labels: refactor

#121 설정 파일 수정
  package.json
Labels: config

#123 배포를 위한 환경 설정
  .gitignore
  package-lock.json
  package.json
  src/index.js
Labels: config

#124 변경사항 메인 브랜치로 병합
  .gitignore
  package-lock.json
  package.json
  src/index.js
Labels: config

#126 메인 브랜치로 병합
  package-lock.json
  package.json
Labels: config
