Repository Cheers-Project/Cheers-Back, pull requests merged in 2022-03, with the labels that each got.

#3 로그인 API 연동 테스트
  package-lock.json
  package.json
  src/index.js
Labels: feature

#5 서버와 DB 연동
  .eslintrc
  package-lock.json
  package.json
  src/index.js
Labels: feature, config

#6 환경 변수 분리
  .gitignore
  package-lock.json
  package.json
  src/index.js
Labels: config

#9 유저 모델, 스키마 구현
  src/index.js
  src/models/user.js
Labels: feature

#11 유저 스키마 수정
  src/api/index.js
  src/api/user/index.js
  src/api/user/userController.js
  src/index.js
  src/models/user.js
Labels: feature

#12 로그인 API 구현
  src/api/user/index.js
  src/api/user/userController.js
Labels: feature

#15 JWT 토큰 발급
  package-lock.json
  package.json
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#16 회원가입 API 구현
  package-lock.json
  package.json
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#20 회원가입 API 수정
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#22 유저 프로필 이미지 저장 구현
  .gitignore
  package-lock.json
  package.json
  src/api/user/index.js
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#27 유저 프로필 이미지 저장 구현
  package-lock.json
  package.json
  src/api/user/index.js
  src/api/user/userController.js
  src/config/s3.js
  src/models/user.js
Labels: feature

#29 config 디렉토리 설정 추가
  .gitignore
Labels: config

#30 카카오 로그인 닉네임 설정하여 JWT 발급
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#31 카카오 로그인
  package-lock.json
  package.json
  src/api/auth/authController.js
  src/api/auth/index.js
  src/api/index.js
  src/api/user/userController.js
  src/index.js
Labels: feature

#33 카카오 로그인 api 리팩토링
  package-lock.json
  package.json
  src/api/auth/authController.js
  src/api/auth/index.js
  src/index.js
Labels: refactor

#35 근처 모임 API 구현
  src/api/index.js
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
  src/models/meeting.js
  src/models/user.js
Labels: feature

#37 근처 모임 요청 API 수정
  src/api/meeting/index.js
  src/api/meeting/meetingController.js
  src/api/user/userController.js
  src/middleware/jwtMiddleware.js
  src/models/meeting.js
  src/models/user.js
Labels: refactor, feature

#39 jwt 로직 변경
  src/models/user.js
Labels: feature

#40 카카오 로그인 시 리프레쉬 토큰 발급 기능 추가
  src/api/auth/authController.js
Labels: feature

#42 로그아웃 API 구현
  src/api/user/index.js
  src/api/user/userController.js
  src/models/user.js
Labels: feature

#44 유저 정보 API 구현
  src/api/user/index.js
  src/api/user/userController.js
Labels: feature

#45 유저 정보 요청 함수 변수명 수정
  src/api/user/index.js
  src/api/user/userController.js
Labels: refactor

#46 유저 정보 API 토큰 유무에 따른 로직 리팩토링
  src/api/user/userController.js
Labels: refactor

#49 회원가입 API 리팩토링
  src/api/user/userController.js
  src/models/user.js
Labels: refactor

#53 카카오 로그인 에러 처리 추가
  src/api/user/userController.js
Labels: feature

#54 회원가입 API 유저 프로필 제거
  src/api/user/index.js
  src/api/user/userController.js
Labels: refactor

#55 유저 프로필 기본 이미지 설정
  src/models/user.js
Labels: feature

#56 유저 프로필 수정, 제거 API 구현
  src/api/auth/authController.js
  src/api/user/index.js
  src/api/user/userController.js
  src/middleware/jwtMiddleware.js
  src/models/user.js
Labels: feature
