Repository Cheers-Project/Cheers-Back, pull requests merged in 2022-05, with the labels that each got.

#127 cors 설정 추가
  src/index.js
Labels: bug

#128 변경 사항 메인 브랜치로 병합
  src/index.js
Labels: feature

#130 오늘 이전 날짜 모임 필터링 기능 추가
  package-lock.json
  package.json
  src/api/meeting/meetingController.js
Labels: feature

#131 모임 필터링 기능 추가 후 메인 브랜치로 병합
  package-lock.json
  package.json
  src/api/meeting/meetingController.js
Labels: feature

#133 게시물 댓글 수 증가 수정
  src/api/comment/commentController.js
Labels: refactor

#138 브랜치 병합
  src/api/user/index.js
  src/api/user/userController.js
Labels: refactor

#139 변수명 수정
  src/models/comment.js
Labels: refactor

#141 닉네임, 프로필 이미지 변경 버그 수정
  src/api/my/myController.js
Labels: fix

#142 메인 브랜치로 병합
  src/api/my/myController.js
  src/models/comment.js
Labels: fix

#144 댓글 수 감소 버그 수정
  src/api/comment/commentController.js
Labels: fix

#147 댓글 작성자 정보 수정 버그 수정
  src/api/comment/commentController.js
Labels: fix

#150 게시물 작성자 수정 버그 수정
  src/api/board/boardController.js
Labels: fix

#153 게시글 작성 버그 수정
  src/middleware/sanitizeHtmlMiddleware.js
Labels: fix

#156 모임 작성 시 작성자 프로필 변경 사항 반영되지 않는 문제 수정
  src/api/board/boardController.js
  src/api/meeting/meetingController.js
Labels: fix

#157 변경 사항 메인 브랜치로 병합
  src/api/board/boardController.js
  src/api/meeting/meetingController.js
Labels: fix

#159 모임 리스트 요청 API 리팩토링
  src/api/meeting/meetingController.js
Labels: refactor

#163 변경 사항 메인 브랜치로 병합
  src/api/meeting/meetingController.js
Labels: refactor

#165 댓글 리스트 삭제 버그 수정
  src/api/board/boardController.js
  src/api/meeting/meetingController.js
Labels: fix

#169 모임 삭제 오류 수정
  src/api/meeting/meetingController.js
Labels: fix
